### PR TITLE
Use llama instead of libllama in `[DllImport]`

### LINKED ISSUE #463: DllImport should not be prefixed with lib
The usage of `[DllImport("libllama")]` results in the windows binaries being prefixed with "lib".
The native libraries in the NuGet packages have renamed DLLs. This makes it annoying to copy in llama binary releases for windows, for testing purposes. If the DLL imports were replaced with just `[DllImport("llama")]`, this issue would not exist on windows, and on other platforms libllama.so and dylibs would work too, even with the lib prefix.

From: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/native-library-loading

> When running on Windows, the DLL is searched for in the following order:
>
> `nativedep`
> `nativedep.dll` (if the library name does not already end with .dll or .exe)
>
> When running on Linux or macOS, the runtime will try prepending lib and appending the canonical shared library extension. On these OSes, library name variations are tried in the following order:
>
> `nativedep.so` / `nativedep.dylib`
> `libnativedep.so` / `libnativedep.dylib`
> `nativedep`
> `libnativedep`

### PR DESCRIPTION
**Pull request by jasoncouture**
This results in windows users not needing to rename the DLL. This allows native llama builds to be dropped in, even on windows.

I also took the time to update the documentation, removing references to renaming the files, since the names now match.

Fixes #463

### CODE REVIEW

**Comment by martindevans** [comment]
This looks like a great fix, thanks very much.

**Comment by jasoncouture** [comment]
Looks like it needs a small tweak to the manual path search logic to work on OS X/Linux, I'll get that pushed soon.

**Comment by jasoncouture** [comment]
Should be fixed in that commit:
image

**Comment by martindevans** [comment]
Thanks!

I'll run a new build and update #460 with new binaries right now.

**Comment by jasoncouture** [comment]
@martindevans when I run this in my fork, it always uses master anyway.
I'm looking into it.

**Pull request merged**
