### PR TITLE
KernelMemory EmbeddingMode bug correction

### PR DESCRIPTION
**Pull request by zsogitbe**

### CODE REVIEW

**Comment by martindevans** [comment]
What's the purpose of this change?

**Comment by AI-TOOLKIT** [comment]
> What's the purpose of this change?

It is a bug correction.  You can test why it is needed by running the KernelMemory example (it will crash without it).

**Comment by zsogitbe** [comment]
> What's the purpose of this change?

It is a bug correction. You can test why it is needed by running the KernelMemory example (it will crash without it).

**Comment by martindevans** [comment]
Thanks!

**Pull request merged**
