### PR TITLE
Removed unused properties of `InferenceParams` & `ModelParams`

### PR DESCRIPTION
**Pull request by martindevans**
I noticed that these properties are unused.

### CODE REVIEW

**Comment by martindevans** [comment]
I'm leaving this open for a while, just in case anyone wants to say that actually we should keep these properties and implement them properly.

**Comment by saddam213** [comment]
Wondering if renaming `ModelAlias` to `Name` would be beneficial

Not an issuse for LLamaSharp itself, but if you are dealing with multiple models it could be handy to have a identifier/display name other than filepath

This is also something end users can esily add themselfs, so maybe not

**Comment by martindevans** [comment]
I'm not against adding something like that. I'm only proposing this PR because right now the properties are totally unused, but if you want to open a PR to implement any of these things I'll happily review it.

For the proposed `Name` property are you thinking it would tag the `LLamaWeights` object with the name (public readonly property), to make it easier to identify? That's not a bad idea.

**Comment by saddam213** [comment]
That what I was thinking, but users could just name thier model files a bit clearer and that would also work

And thinking about it more, `Name` would really be more of a field requiered if dealing with multiple models, and in that case users would most likely need an `Id` field too, so they would most likely create thier own classess from the interfaces anyway

Ignore my old man ramblings :p

**Pull request merged**
