### PR TITLE
LLamaSharpCpp - combine C# and C++ solution

### PR DESCRIPTION
**Pull request by zsogitbe**
This is the final result of my experimentation with the simplest solution I have found. One more step could be done by adding a clever script to pre-configure llama.cpp with the required settings (GPU, AVX2, platform...) and even full automatic build.

### CODE REVIEW

**Comment by zsogitbe** [comment]
I have tried to push this to the experimental_cpp branch from my GitHub desktop, but I have the impression that they have a bug because it seems to go to the main branch. Can you rewire this to experimental_cpp?

**Comment by AsakusaRinne** [comment]
> I have tried to push this to the experimental_cpp branch from my GitHub desktop, but I have the impression that they have a bug because it seems to go to the main branch. Can you rewire this to experimental_cpp?

Hi, sorry but I think I didn't get that. Did you mean to merge master branch to experimental_cpp branch?

**Comment by zsogitbe** [comment]
I wanted to push my solution to experimental_cpp, but I think that it goes to the master branch for some reason. If you think that it is OK to merge it into the master, then it is OK for me. But if you want it in experimental_cpp, then maybe you can change its destination as maintainer!? This is some kind of problem in GitHub desktop I think.

**Comment by martindevans** [comment]
@zsogitbe I've changed it to go to experimental_cpp for you :)

**Comment by zsogitbe** [comment]
Rinne told me that I have full permissions on the [experimental_cpp](https://github.com/zsogitbe/LLamaSharp/tree/experimental_cpp) but the pull do not merge automatically. Do I still need to do something?

**Comment by martindevans** [comment]
I'm not sure, I don't have the correct permissions to view those settings. I can merge this one in if you want though?

**Comment by AsakusaRinne** [comment]
> Rinne told me that I have full permissions on the [experimental_cpp](https://github.com/zsogitbe/LLamaSharp/tree/experimental_cpp) but the pull do not merge automatically. Do I still need to do something?

Hi, sorry for this confusion. Github hasn't supported adding permission for a specified branch yet, so I didn't open the write access for you. However, since this branch is not the master branch, we will merge your pull requests without any review if you want. :)

**Comment by zsogitbe** [comment]
Thank you for merging. The aim is of course to start a discussion about this possible solution for the future...
Maybe it then does not have too much sense to have the experimental branch. Maybe a draft pull or kept open pull request is better!?

**Comment by AsakusaRinne** [comment]
For me both is okay. It actually depends on you. If a long term is required to complete this feature, I'd recommend to keep a branch for it. Otherwise a draft PR is enough.

Note that since this approach is a different way with which we are currently on, we might not accept it unless many users like your idea. But anyway, thank you very much for your contribution! It has already provided a good idea for LLamaSharp.

**Comment by zsogitbe** [comment]
OK! Let us keep it in the experimental branch. You know about it now and you can think about it without the pressure to approve or reject.

**Comment by AsakusaRinne** [comment]
I will let the users know your approach after you have completed it. :)

Merging this PR now.

**Pull request merged**
