### PR TITLE
Checkout specific ref for llamacpp when building native libs

### PR DESCRIPTION
**Pull request by jasoncouture**

### CODE REVIEW

**Comment by martindevans** [comment]
Thanks

**Comment by jasoncouture** [comment]
When I run this in my branch, it ends up always using master. I'm debugging it now.

**Comment by martindevans** [comment]
Oops, I guess I was a bit too quick on the merge there 😆

**Comment by martindevans** [comment]
@jasoncouture it looks like it should be `github.event.inputs.` instead of `github.input.events.` according to [docs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs)

**Pull request merged**
