### PR TITLE
Add Rosetta2 Binaries

### LINKED ISSUE #752: LLamaSharp runtime binaries don't support Rosetta2
### Description

Hi there,

I'm attempting to integrate LLamaSharp with a C#-based game that is stuck with Rosetta emulation on M1 Macs. Unfortunately, the regular builds are compiled with AVX (I believe?) which Rosetta can't emulate, causing a crash. I compiled with minimal support from the Llama.cpp repo and it works fine. 

I'm not sure if this is something that needs to be addressed by the library itself, but felt worth noting here.

### PR DESCRIPTION
**Pull request by abhiaagarwal**
Closes #752. I make the assumption that "if x86 and doesn't have AVX, then it is rosetta2". My understanding is that all modern (>2015)-based Intel CPUs used on Macbooks have AVX, so checking for AVX under a x86 environment is a good enough proxy for "under Rosetta2".

### CODE REVIEW

**Comment by abhiaagarwal** [comment]
https://github.com/abhiaagarwal/LLamaSharp/actions/runs/9237231679/job/25413958437 Artifacts

**Comment by SignalRT** [comment]
> https://github.com/abhiaagarwal/LLamaSharp/actions/runs/9237231679/job/25413958437 Artifacts

@abhiaagarwal, it seems that the step to Gather binaries fail in linked execution. I would appreciate If you can check this.

The other thing that seems strange to me is to name this as something related with rosetta. Any intel osx without avx support is included in this use case (including rosetta emulation). Am I right or I'm missing something?.

**Comment by abhiaagarwal** [comment]
I'll fix the issue! Missing adding the folder name in `mkdir`.

> The other thing that seems strange to me is to name this as something related with rosetta. Any intel osx without avx support is included in this use case (including rosetta emulation). Am I right or I'm missing something?.

Yes, but at least in regards to Macbooks on Intel, non-AVX hardware doesn't really exist anymore. I did a search and the last chip in an Intel Macbook was in 2014. I named it Rosetta2 to make it more clear to anyone poking around *why* these binaries exist, but I don't really have a strong opinion otherwise. More than happy to rename it to `nonavx` if desired.

**Comment by martindevans** [comment]
@abhiaagarwal Could you start another test run on your repo please. If that works we can merge this :)

**Comment by abhiaagarwal** [comment]
@martindevans absolutely! Fixed the mkdir issue and triggered a new run here. https://github.com/abhiaagarwal/LLamaSharp/actions/runs/9294309458

**Comment by abhiaagarwal** [comment]
Seems like the hardest thing I've ever done is properly creating directories... here's a run that succeeded. https://github.com/abhiaagarwal/LLamaSharp/actions/runs/9294794909

**Comment by martindevans** [comment]
Looks good to me! @SignalRT I think this is ready to merge if it looks ok to you?

**Comment by AsakusaRinne** [comment]
There's one more thing: could you please add the binaries to [this nuspec file](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec), so that it will get published in our next release?

Besides, @martindevans @SignalRT do you think it's a good idea to separate the MAC backend package from `LLamaSharp.Backend.Cpu`? Actually MAC binaries are not "pure" CPU ones because they may take use of metal.

**Comment by martindevans** [comment]
> do you think it's a good idea to separate the MAC backend package from LLamaSharp.Backend.Cpu?

Seems like a good idea to me, it's a good way to shrink the CPU backend package down a bit.

**Comment by abhiaagarwal** [comment]
If you can open a new branch on this repo, I can change this PR to merge against that? I'm not familiar with dotnet packaging, but a mac-specific backend is for sure a good idea.

**Comment by SignalRT** [comment]
The PR it's ok for me. I would not separate the backend at this moment. In my opinion the point that rest is to add de libraries to the [nuspec](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec)

**Comment by abhiaagarwal** [comment]
Updated the nuspec. Do y'all want me to squash merge?

**Review by SignalRT — APPROVED** [review]
It seems OK to me.

**Comment by martindevans** [comment]
No need for you to squash, we can squash-and-merge :)

**Pull request merged**
