### PR TITLE
Binary Update Jan 2024

### PR DESCRIPTION
**Pull request by martindevans**
Built with https://github.com/SciSharp/LLamaSharp/actions/runs/7674546118/job/20919306901, llama.cpp commit [`a1d6df129bcd3d42cda38c09217d8d4ec4ea3bdd`](https://github.com/ggerganov/llama.cpp/tree/a1d6df129bcd3d42cda38c09217d8d4ec4ea3bdd)

### CODE REVIEW

**Comment by martindevans** [comment]
Testing:
 - [x] Windows (CPU)
 - [ ] Windows (GPU)
 - [ ] Linux (CPU)
 - [ ] Linux (GPU)
 - [ ] MacOS

**Comment by Theoistic** [comment]
Ran the LLama.Examples using phi-2.Q5_K_M.gguf .. works perfectly on CPU. 
not tested on GPU.
Machine: Windows 11 .. Intel i5-10400F .. 16GB Ram .. nvidia 1660 Super

**Comment by SignalRT** [comment]
@martindevans  It works on osx-arm64 metal.

**Comment by jasoncouture** [comment]
Tested CUDA on an A2000, works flawlessly.

**Comment by martindevans** [comment]
Thanks for testing @jasoncouture. Was that test on Windows or Linux?

**Comment by martindevans** [comment]
@jasoncouture has been doing some work on binaries (renaming them in #465 and adding CLBLAST in #468). I'll re-run the build step and update this PR based on those changes soon.

**Comment by jasoncouture** [comment]
> a1d6df129bcd3d42cda38c09217d8d4ec4ea3bdd

Sorry, @martindevans , that was windows.

**Comment by jasoncouture** [comment]
I also tested linux CPU, that also works fine.

**Comment by martindevans** [comment]
Closing this PR, various changes have been made to the binaries in some other PRs. I'll open a new one soon.

**Pull request closed without merging**
