### PR TITLE
fix: add cuda llava native libraries.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
The files are from [Action 8518332362](https://github.com/SciSharp/LLamaSharp/actions/runs/8518332362), with no updating for llama.cpp commit.

### CODE REVIEW

**Comment by martindevans** [comment]
One of the files is called `LLama\runtimes\deps\cu11.7.1\libllama_shared.so`, should that be `LLama\runtimes\deps\cu11.7.1\libllava_shared.so` (lla**v**a instead of lla**m**a)?

**Comment by AsakusaRinne** [comment]
> One of the files is called `LLama\runtimes\deps\cu11.7.1\libllama_shared.so`, should that be `LLama\runtimes\deps\cu11.7.1\libllava_shared.so` (lla**v**a instead of lla**m**a)?

Yes, I misspelled that in the workflow. I have fixed this typo and manually renamed the file before submitting this PR.

**Comment by AsakusaRinne** [comment]
@martindevans I think we should publish a patch release since it's a severe performance issue, as shown in #639 and #650. Do you have other works that want to be included together in 0.11.2?

**Comment by martindevans** [comment]
Shall we merge #649 and then do a patch release with this PR?

We'll probably need to do another patch release in a few days to fix the publish issue we were discussing on Discord. That's not really a problem though.

**Comment by AsakusaRinne** [comment]
> Shall we merge https://github.com/SciSharp/LLamaSharp/pull/649 and then do a patch release with this PR?

I think it's a good idea.

> We'll probably need to do another patch release in a few days to fix the publish issue we were discussing on Discord. That's not really a problem though.

That's why it's called patch release! :)

**Comment by martindevans** [comment]
@AsakusaRinne #649 has been reviewed and merged, you can go ahead and merge this one when you're ready :)

**Pull request merged**
