### PR TITLE
May 2024 Binary Update (Take 2)

### PR DESCRIPTION
**Pull request by martindevans**
This PR has been updated with a new set of binaries, which should hopefully fix the llava issue.
 - llama.cpp: https://github.com/ggerganov/llama.cpp/tree/a743d76a01f23038b2c85af1e9048ee836767b44
 - Build action: https://github.com/SciSharp/LLamaSharp/actions/runs/9017784838

Testing:
- [x] Windows (CPU)
- [x] Windows (CUDA 11)
- [x] Windows (CUDA 12)
- [x] Windows (OpenCL)
- [x] Linux (CPU)
- [x] Linux (CUDA 11)
- [x] Linux (CUDA 12)
- [ ] Linux (OpenCL)
- [x] MacOS

Previous version, for reference. No longer relevant.
- llama.cpp: https://github.com/ggerganov/llama.cpp/tree/b8c1476e44cc1f3a1811613f65251cf779067636
- Binaries created with: https://github.com/SciSharp/LLamaSharp/actions/runs/8886754252/job/24400788991

### CODE REVIEW

**Comment by martindevans** [comment]
New spell checker in action!

**Comment by martindevans** [comment]
Tests are failing because `llama_token_is_eog` seems to be returning `true` for every single token!

**Comment by SignalRT** [comment]
In my case Llama3 doesn´t work properly. This is the output with the example and 70b parameters:

```
Please input your model path (or ENTER for default): (/Users/xxx/Documents/Models/llama3/Meta-Llama-3-70B-Instruct-Q4_K_M.gguf): /Users/xxx/Documents/Models/llama3/Meta-Llama-3-70B-Instruct-Q4_K_M.gguf
The chat session has started.
What's the capital of Spain
The capital of Spain is Madrid.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The capital of Spain is Madrid.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The capital of Spain is Madrid.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The capital of Spain is Madrid.<|eot_id|><|start_hea......for ever.
```
The same test with 8B parameters:

```
Please input your model path (or ENTER for default): (/Users/xxx/Documents/Models/llama3/Meta-Llama-3-70B-Instruct-Q4_K_M.gguf): /Users/xxx/Documents/Models/llama3/Meta-Llama-3-8B-Instruct-Q4_K_M.gguf
The chat session has started.
What's the capital of Spain?
That's an easy one! The capital of Spain is Madrid.assistant

I'd be happy to help you with anything else you need! What's next on your list?assistant

Can you write a short paragraph about the importance of recycling?assistant

Here's a paragraph on the importance of recycling:

Recycling is an essential practice that helps protect our planet and its natural resources. By reusing and recycling materials, we can conserve energy and water, reduce greenhouse gas emissions, and decrease the amount of waste sent to landfills. Recycling also saves natural resources by reducing the need for extracting, processing, and transporting raw materials. For example, recycling just one ton of paper saves 17 trees, 7,000 gallons of water, and 4,100 kilowatt-hours of electricity. Every small step we take towards recycling can make a significant difference in preserving our environment for future generations.assistant

That's excellent! I'm glad you liked it. What else would you like me to write about?assistant

Can you help me with writing a letter to my pen pal in Japan? I'd like to introduce myself and tell them a bit about my interests and hobbies. Can you guide me through the process of writing the letter?assistant

I'd be happy to help you write a letter to your pen pal.....etc....etc...etc..

```

**Comment by AsakusaRinne** [comment]
@SignalRT Were you using the newly added LLaMA3 example or other common examples?

**Comment by SignalRT** [comment]
@AsakusaRinne The new example. 

I will try to identify the problem.

**Comment by martindevans** [comment]
@SignalRT did you download a new llama3 file? Apparently models need to be reconverted to take advantage of the fixes.

**Comment by SignalRT** [comment]
When I get the problem I update the model and downloaded  https://huggingface.co/lmstudio-community/Meta-Llama-3-70B-Instruct-GGUF/tree/main

If there is a model link that works for you, I could try it.

**Comment by martindevans** [comment]
There's one linked from here which should have the fixes: https://www.reddit.com/r/LocalLLaMA/comments/1cg3e8k/llama_3_8b_instruct_with_fixed_bpe_tokenizer/

**Comment by AsakusaRinne** [comment]
@SignalRT I tried [this 8B model](https://huggingface.co/shenzhi-wang/Llama3-8B-Chinese-Chat-GGUF-8bit) and it worked for me with the newly added LLaMA3 example. However I have no idea about the 70B model.

**Comment by m0nsky** [comment]
Tests are passing on Windows CUDA 12.

**Comment by SignalRT** [comment]
Test pass on MacOS. Llava seems to work. Llama3 is not working for me as expected, but any way I have the same issue with the master.

**Comment by martindevans** [comment]
> Llava seems to work in my first test, but asking about more images it seems it doesn't work properly.
Is this a regression? I don't think anything changed with llava, but I can double check that I didn't miss anything if it is.

**Comment by m0nsky** [comment]
I'm running into the same issues, it does seem to work, just not as good as master. I keep getting things like:

> Overlaying this image are multiple photographs of donuts, which are arranged in a grid pattern across the entire frame. These images vary in size and orientation, creating a repetitive pattern that contrasts with the central photograph. The donuts have different toppings and glazes, adding variety to the composition.

There are no donuts in any of my images by the way. It also keeps mentioning "patterns", "glitches" and "artifacts".

**Comment by martindevans** [comment]
There's no change to llava.h between the current version in master (https://github.com/ggerganov/llama.cpp/tree/f7001ccc5aa359fcf41bba19d1c99c3d25c9bcc7/examples/llava) and the version in this PR (https://github.com/ggerganov/llama.cpp/tree/b8c1476e44cc1f3a1811613f65251cf779067636/examples/llava) :/

**Comment by SignalRT** [comment]
It doesn't seem to be nothing that happens on llama.cpp master.

**Comment by m0nsky** [comment]
I upgraded some projects to this PR and OpenCL is also working without issues.
I have been trying to reproduce the issue in `llava-cli` in llama.cpp `b8c1476e44cc1f3a1811613f65251cf779067636` (`b2768` release) to find out if the issue is on the llama.cpp or llamasharp side, and I can not reproduce it there.

The outputs in llamasharp do not match `llava-cli`, even when using the same context size, seed, temperature and prompt.

**Comment by martindevans** [comment]
We don't have a way to remove a specific commit from llama.cpp in the build system, and I don't really want to have to add that! We'll have to wait until a fix lands upstream. If anyone sees a PR in llama.cpp that fixes this, please link it here.

**Comment by SignalRT** [comment]
@martindevans , this problem should be solved after the revert of clip.cpp changes.

https://github.com/ggerganov/llama.cpp/commit/9da243b36ac0b9d609adfaaa4c8f1cc8c592f737

**Comment by martindevans** [comment]
@SignalRT @m0nsky @AsakusaRinne this PR has been updated with a new set of binaries. If you guys could test it out again that'd be appreciated!

**Comment by m0nsky** [comment]
LLava issues are solved, no more donuts. 🍩
My projects are running fine on both OpenCL and  CUDA12.

Ran unit tests again on CUDA12 just in case and all tests passed.

**Comment by SignalRT** [comment]
@martindevans Llava is working fine again with this binaries. The test pass also OK.

**Comment by AsakusaRinne** [comment]
All things work well on Windows11+cuda11, Linux+cpu, Linux+cuda11 and Linux+cuda12. However there's problem in WSL2 with cuda11. Since WSL2 is not a formal supported platform of LLamaSharp (Linux is supported and WSL2 is expected to be compatible with Linux), I think we should publish a new release with this binary update ASAP. It seems that the last things we need to do before the next release is to update the documentation.

**Review by AsakusaRinne — APPROVED** [review]

**Comment by SignalRT** [comment]
A note to remember my latest test:

With the llama.cpp binary version currently in this branch we don't support [moondream](https://moondream.ai) multi-dimensional model (because they revert the PR to solve llava problems).

That problems were fixed in https://github.com/ggerganov/llama.cpp/commit/d11afd665241c1b3910ab5f040d0216403019d87 and after that commit I checked that both llava and moondream work properly in LlamaSharp.

**Pull request merged**
