### PR TITLE
Update Semantic Kernel & Kernel Memory Package

### PR DESCRIPTION
**Pull request by xbotter**
**Summary**:
This pull request updates the LLama.SemanticKernel and LLama.Unittest projects. The changes include modifying the LLamaSharpChatCompletion class in the LLama.SemanticKernel project to use the ILLamaExecutor interface instead of the StatelessExecutor class. Additionally, the LLama.Unittest project is updated to include references to the Moq and System.Linq.Async packages. Two new test classes, ExtensionMethodsTests and LLamaSharpChatCompletionTests, are added to the LLama.Unittest project to test the extension methods and LLamaSharpChatCompletion class, respectively.

**Changes**:
- Modified the LLamaSharpChatCompletion class in the LLama.SemanticKernel project to use the ILLamaExecutor interface instead of the StatelessExecutor class.
- Added references to the Moq and System.Linq.Async packages in the LLama.Unittest project.
- Added a new test class, ExtensionMethodsTests, to test the extension methods.
- Added a new test class, LLamaSharpChatCompletionTests, to test the LLamaSharpChatCompletion class.
- Added LLamaSharpTextCompletionTests class to the LLama.Unittest project.
- Updated package references in the LLama.Examples project to use Microsoft.KernelMemory.Core version 0.34.240313.1, Microsoft.SemanticKernel version 1.6.2, and Microsoft.SemanticKernel.Plugins.Memory version 1.6.2-alpha.
- Updated package references in the LLama.KernelMemory project to use Microsoft.KernelMemory.Abstractions version 0.34.240313.1.
- Updated package references in the LLama.SemanticKernel project to use Microsoft.SemanticKernel.Abstractions version 1.6.2.

### CODE REVIEW

**Comment by martindevans** [comment]
Does this supersede #590, #591 or #592?

**Comment by xbotter** [comment]
> Does this supersede #590, #591 or #592?

yep

**Comment by martindevans** [comment]
I'll close those ones then.

**Comment by AsakusaRinne** [comment]
Many thanks for this contribution!

**Pull request merged**
