### PR TITLE
Added a converter similar to the Open AI one

### PR DESCRIPTION
**Pull request by futzy314**
This is all based on the same classes in their OpenAI implementation.  I tested it with a couple of Microsoft's sample projects in Semantic Kernel, and it seems to work.  I didn't see any unit tests for the Semantic Kernel code yet, but if you want to start adding that, I can add some unit tests too.

Fixes SciSharp/LlamaSharp#313

### CODE REVIEW

**Comment by AsakusaRinne** [comment]
Thank you for the contribution! If you would like to, we'll appreciate it if you could add some unit test about semantic-kernel. Note that this is not a required one, the overall looks very good to me. :)

**Review by xbotter — APPROVED** [review]
LGTM.

**Comment by futzy314** [comment]
OK, I can work on some unit tests too, will add here.  One other suggestion, I think the ChatRequestSettings class is misnamed, because it doesn't just apply to Chat, it applies to Text as well.  I suggest renaming it to LlamaRequestSettings.

**Comment by yukimakura** [comment]
I was struggling with this very issue just now. Thanks for the great pull request!

**Pull request merged**
