### PR TITLE
Add path to find llama.dll for MAUI

### PR DESCRIPTION
**Pull request by evolcano**
This commit is originally made by [lcarrere](https://github.com/lcarrere) in https://github.com/SciSharp/LLamaSharp/issues/180 .

I have confirmed this modification is OK in my windows 11 laptop, MAUI could load GGUF model and infer successfully.

I make this commit according require of [AsakusaRinne](https://github.com/AsakusaRinne).

### CODE REVIEW

**Comment by martindevans** [comment]
This needs to be skipped on non-Windows platforms, or else it'll fail because the imported method does not exist. e.g. check `System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Windows);` and skipping the call should probably work.

**Comment by evolcano** [comment]
RuntimeInformation.IsOSPlatform(OSPlatform.Windows) is already exist, the imported method AddDllDirectory will only run in windows platform:

```
        private static int GetCudaMajorVersion()
        {
            string? cudaPath;
            string version = "";
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                cudaPath = Environment.GetEnvironmentVariable("CUDA_PATH");
                if (cudaPath is null)
                {
                    return -1;
                }

                //Ensuring cuda bin path is reachable. Especially for MAUI environment.
                string cudaBinPath = Path.Combine(cudaPath, "bin");

                if (Directory.Exists(cudaBinPath))
                {
                    AddDllDirectory(cudaBinPath);
                }

                version = GetCudaVersionFromPath(cudaPath);
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                // Try the default first
                cudaPath = "/usr/local/bin/cuda";
                version = GetCudaVersionFromPath(cudaPath);
                if (string.IsNullOrEmpty(version))
                {
                    cudaPath = Environment.GetEnvironmentVariable("LD_LIBRARY_PATH");
                    if (cudaPath is null)
                    {
                        return -1;
                    }
                    foreach (var path in cudaPath.Split(':'))
                    {
                        version = GetCudaVersionFromPath(Path.Combine(path, ".."));
                        if (string.IsNullOrEmpty(version))
                        {
                            break;
                        }
                    }
                }
            }

            if (string.IsNullOrEmpty(version))
                return -1;

            version = version.Split('.')[0];
            if (int.TryParse(version, out var majorVersion))
                return majorVersion;

            return -1;
        }
```

@martindevans, did I missed something?

**Comment by martindevans** [comment]
Ah sorry, I didn't zoom out far enough in the diff to see that! In that case it all looks fine to me.

**Review by martindevans — APPROVED** [review]

**Review by AsakusaRinne — APPROVED** [review]
LGTM, thank you a lot for this contribution!

**Pull request merged**
