### PR TITLE
July 2024 binaries

### PR DESCRIPTION
**Pull request by martindevans**
This updates LLamaSharp to a newer llama.cpp version (1c5eba6f8e628fb0a98afb27d8aaeb3b0e136451). Thanks to @m0nsky and @SignalRT for helping out with this!

This includes a couple of other related changes, due to upstream changes:
 - Upgrade from cuda12.1.0 to cuda12.2.0
 - Changed various build defines from LLAMA_X to GGML_X

There is a major change in how binaries are distributed for development. Previously they were committed into this repo, in the [runtimes/deps](https://github.com/SciSharp/LLamaSharp/tree/master/LLama/runtimes/deps) folder. However, the llama.cpp binaries have no grown over 100MB for CUDA, which exceeds the maximum GitHub file size.

To work around this binaries have been uploaded to a release in another repo (currently [here](https://github.com/martindevans/LLamaSharpBinaries/releases/tag/1c5eba6f8e62), ownership will be transferred to SciSharp before this PR is closed). A new msbuild action has been added to LLamaSharp.csproj which automatically downloads and unzips the binaries.

Note that this version is now a week out of date, due to the hold up with the new build system. Once this has merged we may want to immediately do another binary update and then do a release. The important thing here is testing that this new approach works on all platforms!

To do:
 - [x] Testing:
   - [x] Windows (CPU)
   - [x] Windows (CUDA)
   - [x] Windows (Vulkan)
   - [x] Linux CPU
   - [x] Linux CUDA
   - [x] Linux Vulkan
   - [x] MacOS
 - [x] Transfer ownership of binaries repo
   - [x] Update csproj file to download from new URL
 - [x] Update nuspec files to include new `ggml.dll`s

### CODE REVIEW

**Comment by SignalRT** [comment]
@martindevans  I tested it on osx and it's working. I also changed the nuget packages to include sgml.

**Review by SignalRT — APPROVED** [review]
It seems ok to me

**Comment by martindevans** [comment]
Thanks!

**Comment by martindevans** [comment]
The race condition in the build has been fixed, thanks to @m0nsky for the hard work!

**Comment by martindevans** [comment]
- Transferred ownership to SciSharp: https://github.com/SciSharp/LLamaSharpBinaries
 - Updated to pull from new source

**Pull request merged**
